title: 우형이의 포폴사이트
name: Choi woo hyung
email: choiwh000@naver.com
description: >-
  UX and Frontend developer


baseurl: ""
url: "https://cwh915.github.io"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
# facebook_id: babycheetah
instagram_id: dnguddld


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_3.jpg
  title: 안녕하세요. <br>반갑습니다!</br>


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/img_bg_4.jpg
  title: I am<br>UX, Frontend Developer
  subtitle: >- 
    초보 개발자 최우형입니다.


# About
about_meta: About Me
about_header: >- 
  "꿈이 없던 대학생"
about_introduce: >-
  "안녕하세요. UX와 프론트엔드 개발자를 꿈꾸는 주니어 개발자, 최우형입니다."
about_content: >-
  제가 자신있는 분야입니다.
about_services: # 형식에 맞추어 항목 추가
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App
# - icon: icon-phone3
- icon: icon-code
  name: JavaScript
- icon: icon-monitor
  name: UX
about_box_content: <h5>내가 개발자로 취업해서 코딩만 한다면, 그 사람은 단지 벽돌을 나르던 사람이 변형이 되어 코딩을 하는 것과 다름 없다. <br><br>저는 사용자들과 직접 상호작용하는 개발자, 디자이너로서 사용자들의 즐거움까지 주고싶습니다.</h5>
about_box_button:
  link: https://choiwh000.github.io/
  name: BLOG


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 앞으로 더 발전할 것입니다.
tech_list: # 형식에 맞추어 항목 추가
- name: HTML
  color: color-2
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: HTML 기초, HTML 마크업 언어의 기본적인 문법에 대해 알고 있고, 퍼블리싱을 통해 공부하였습니다.
- name: CSS
  color: color-4
  animation: fadeInRight
  percent: 60
  mark: 60
  content: 공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. CSS 기본부터 다시 배우겠다는 마음으로 공부하고 있습니다.
- name: JavaScript
  color: color-3
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 자바스크립트 기초, 알고리즘을 공부하고 자바스크립트 언어의 기본적인 문법에 대해 알고 있으며, 다양한 프로젝트를 자바스크립트를 사용하였습니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 40
  mark: 40
  content: 대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
tech_desc: 앞으로 더 발전하기 위해서 <strong>javascript, React, jQuery </strong>등을 계속해서 조금씩 공부할 계획입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>개인 프로젝트</span><span>팀 프로젝트</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: Frontend

project_my: # 형식에 맞추어 항목 추가
- background_url: images/pofol/movie/main.JPG
  animation: fadeInLeft
  name: 영화 검색 사이트 - 개인
  description: 영화 API를 활용하여 영화 정보 제공사이트를 제작하였습니다.
  detail_url: https://choiwh000.github.io/Movies/
  readmore_url: https://choiwh000.github.io/portfolio/fe-p/2021-12-30-movie-site/

- background_url: images/pofol/withhome/main.JPG
  animation: fadeInLeft
  name: With-Home - 개인
  description: 기존 사이트를 React를 활용하여 새로운 코드로 제작해보았습니다.
  detail_url: https://choiwh000.github.io/WithHome/
  readmore_url: https://choiwh000.github.io/portfolio/fe-p/2022-01-15-withhome/

- background_url: images/pofol/Sketch-book/home.JPG
  animation: fadeInLeft
  name: Sketch-book - 개인
  description: Canvas를 활용하여 스케치북을 제작하였습니다.
  detail_url: https://choiwh000.github.io/Paint-JS/
  readmore_url: https://choiwh000.github.io/portfolio/fe-p/2021-12-07-sketch-book/

- background_url: images/pofol/todolist/home.JPG
  animation: fadeInLeft
  name: Todo-List - 개인
  description: VanillaJS를 활용한 연습용 투두리스트입니다.
  detail_url: https://choiwh000.github.io/Vanilla-JS/
  readmore_url: https://choiwh000.github.io/portfolio/fe-p/2021-11-28-to-do-list/

- background_url: images/pofol/vr/main.JPG
  animation: fadeInRight
  name: VR-Contents - 팀
  description: Three.js를 활용하여 VR콘텐츠를 제작하였습니다.
  detail_url: https://choiwh000.github.io/portfolio/fe-p/2021-06-30-vr-contents/
  readmore_url: https://choiwh000.github.io/portfolio/fe-p/2021-06-30-vr-contents/



project_team_name: UX Design
project_team: # 형식에 맞추어 항목 추가
- background_url: images/pofol/zolzak-site/zolzak-site.png
  animation: fadeInRight
  name: 졸업전시회 사이트 리뉴얼 - 팀
  description: 본 졸업작품사이트는 보다 학생 친화적인 정보구성에 초점을 맞춘 사이트입니다.
  detail_url: https://su-aj815.github.io/Graduation-Works-Site/
  readmore_url: https://choiwh000.github.io/portfolio/ux-p/2021-12-20-zolzak_site_ux/

- background_url: images/pofol/sunheng/main.JPG
  animation: fadeInLeft
  name: 선행인터렉션 디자인 - 개인
  description: 본 연구에서는 UX/UI와 첨단기술을 기반에 둔 독창적이고 창의적인 아이디어 발굴과 아이디어의 인터랙션 개념 표현법을 담고 있습니다.
  detail_url: https://choiwh000.github.io/portfolio/ux-p/2021-12-27-sunheng/
  readmore_url: https://choiwh000.github.io/portfolio/ux-p/2021-12-27-sunheng/

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: 인프런강의(2021~)
#   description: >-
#     취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#     또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
#     많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
#     공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 디자이너, 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 분위기 메이커
  color: color-1
  icon: icon-bulb
  content: 다양한 프로젝트를 진행하면서 모두 분위기 메이커 역할을 통해 팀원들의 사기를 불어넣어줄 수 있습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분, 커뮤니케이션이 익숙합니다. 새로운 프로젝트에 도전적입니다.
exp_counters:
- name: A project in progress
  count: 3
  speed: 3000
- name: project
  count: 7
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 넥슨 PROJECT MOD
  date: 2021.11~2022.03
  content: 넥슨 메타버스 플랫폼에서 크리에이터로 활동 <br> LuaScript를 활용하여 게임 제작 및 PROJECT MOD의 방향성 제시 및 기여
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
# - name: Voice Caddie 산학과제
#   date: 2021.05~2021.10
#   content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
#   color: color-2
#   icon: icon-pen2
#   animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: TECH UNIVERSITY OF KOREA
  subtitle: 한국공학대학교 미디어디자인공학과 학사과정
  date: 2019.03 - 현재
  content: 한국공학대학교 미디어디자인공학과 4학년 재학 중입니다.
# - title: HANSUNG UNIVERSITY
#   subtitle: xx대학교 xx과 졸업
#   date: 20xx.03 - 20xx.02
#   content: 나에대한 간단한 설명글 
- title: JINJEOP HIGH SCHOOL
  subtitle: 진접고등학교
  date: 2016.03 - 2019.02
  # content: >-
  #   설명글
  #   설명글
  #   설명글
  #   설명글


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: MY 블로그
  subtitle: 블로그 운영
  date: 2022.05
  content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영할 것입니다.
  thumbnail_url: images/pofol/blog/main.JPG
  link: #
# - title: 따라쟁이의 유튜브
#   subtitle: 개발,논문 유튜브 채널 운영
#   date: 2018.04
#   content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: images/blog-2.PNG
#   link: #
# - title: 네이버블로그
#   subtitle: 이전 블로그
#   date: 2018.03
#   content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
#   thumbnail_url: images/blog-3.PNG
#   link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: choiwh000@naver.com
  icon: icon-globe-outline
- title: 경기도 남양주시
  icon: icon-map
- title: +82 10 8589 5603
  icon: icon-phone
# - title: 웹 주소
#   icon: icon-layers2
#   url: choiwh000@naver.com
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
